# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]

inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]

# Start a terminal
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
cmd-enter = '''exec-and-forget osascript -e '
tell application "com.github.wez.wezterm"
    activate
end tell'
'''

# Start raycast
cmd-d = '''exec-and-forget osascript -e '
tell application "raycast"
    activate
end tell'
'''

# Change focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Alternatively, you can use the cursor keys
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

# Move focused window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Alternatively, you can use the cursor keys
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# Reload the configuration fil
alt-shift-r = 'reload-config'

# Change container layout (stacked, tabbed, toggle split, toggle fullscreen)
alt-s = 'layout v_accordion'
alt-w = 'layout h_accordion'
alt-t = 'layout tiles horizontal vertical'
alt-f = 'fullscreen'

# Switch to workspace and set workspace names
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# Move focused container to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# Window callbacks

# |__ WHATSAPP __|
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = "move-node-to-workspace 1"

# |__ FINDER __|
[[on-window-detected]]
if.app-id = 'com.apple.Finder'
run = "move-node-to-workspace 2"

# |__ WEZTERM __|
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 2"

# |__ iTERM2 __|
[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = "move-node-to-workspace 2"

# |__ TERMINAL __|
[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = "move-node-to-workspace 2"

# |__ ARC BROWSER __|
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace 3"

# |__ GOOGLE CHROME __|
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 3"

# |__ VSCODE __|
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace 6"

# |__ AFFINITY DESIGNER 2 __|
[[on-window-detected]]
if.app-id = 'com.seriflabs.affinitydesigner2'
run = "move-node-to-workspace 7"

# |__ AFFINITY PHOTO 2 __|
[[on-window-detected]]
if.app-id = 'com.seriflabs.affinityphoto2'
run = "move-node-to-workspace 8"

# |__ SPOTIFY __|
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 10"

